document.addEventListener("DOMContentLoaded",()=>{
  const section=document.querySelector(".champions-centre");if(!section)return;
  section.classList.add("football-centre");
  section.innerHTML=`
<div class="scoreboard-heading champions-heading"><div><p class="eyebrow">UEFA Champions League · 2026/27</p><h2>Centro de resultados</h2><p id="champions-updated"></p><p class="timezone-note">🕒 Horarios adaptados a tu zona</p></div><div class="live-connection"><span class="connection-dot" aria-hidden="true"></span><span><strong>Datos UEFA sincronizados</strong><small>Partidos, resultados y clasificación</small></span></div></div>
<div class="score-strip" id="champions-score-strip" aria-label="Resumen de partidos de Champions"></div>
<div class="football-view-tabs champions-view-tabs" role="tablist" aria-label="Vistas de Champions"><button class="view-button active" data-champions-view="matches" role="tab" aria-selected="true">Partidos</button><button class="view-button" data-champions-view="live" role="tab" aria-selected="false"><span class="live-dot" aria-hidden="true"></span> En directo <span id="champions-live-count" class="view-count">0</span></button><button class="view-button" data-champions-view="results" role="tab" aria-selected="false">Resultados</button><button class="view-button" data-champions-view="standing" role="tab" aria-selected="false">Clasificación</button><button class="view-button" data-champions-view="draw" role="tab" aria-selected="false">Sorteo</button></div>
<div data-champions-panel="matches"><div class="panel-header"><div><h3>Todos los partidos</h3><p>La jornada completa, con horarios locales y acceso al calendario.</p></div><label class="round-picker" for="champions-round-select"><span>Seleccionar jornada</span><select id="champions-round-select"></select></label></div><div class="round-summary"><h3 id="champions-round-title">Jornada</h3><a class="text-link" href="https://www.uefa.com/uefachampionsleague/fixtures-results/" target="_blank" rel="noopener noreferrer">Comprobar en UEFA →</a></div><div id="champions-matches" class="match-list full-round-grid"></div></div>
<div data-champions-panel="live" hidden><div class="view-heading"><div><p class="eyebrow">Ahora mismo</p><h3>Partidos en directo</h3></div></div><div id="champions-live-matches" class="match-list live-results-grid"></div></div>
<div data-champions-panel="results" hidden><div class="view-heading"><div><p class="eyebrow">Marcadores definitivos</p><h3>Resultados de la jornada</h3></div></div><div id="champions-results" class="match-list live-results-grid"></div></div>
<div data-champions-panel="standing" hidden><article class="mini-standing standalone-standing"><h3>Clasificación de la fase de liga</h3><p>1–8 pasan a octavos; 9–24 disputan el play-off.</p><div class="champions-legend"><span class="direct">1–8 · Octavos</span><span class="playoff">9–24 · Play-off</span><span class="out">25–36 · Eliminados</span></div><div id="champions-standing" class="compact-standing"></div></article></div>
<div data-champions-panel="draw" hidden><div class="view-heading"><div><p class="eyebrow">Sorteo oficial</p><h3>Ocho rivales por equipo</h3></div><strong id="champions-countdown">36 equipos confirmados</strong></div><div id="champions-draw-overview"></div></div>
<section id="champions-bracket" class="champions-bracket" hidden><div class="bracket-title"><p class="eyebrow">Camino a Madrid 2027</p><h3>Fase eliminatoria</h3></div><div class="trophy-stage" aria-hidden="true"><span>🏆</span><strong>CHAMPIONS</strong><small>Final · Estadio Metropolitano</small></div><div id="champions-bracket-rounds" class="bracket-rounds"></div></section>`;
});
