function isFootballLive(match){if(match.state==="live")return true;if(match.state||!match.iso)return false;const elapsed=Date.now()-new Date(match.iso).getTime();return elapsed>=0&&elapsed<3*60*60*1000;}

document.addEventListener("DOMContentLoaded", async () => {
  await window.f1Ready;
  const state=getF1State(),name=document.getElementById("f1-name"),place=document.getElementById("f1-circuit"),session=document.getElementById("f1-next-session"),timer=document.getElementById("f1-countdown");
  if(state.race){name.textContent=state.race.name;place.textContent=`📍 ${state.race.circuit}`;session.textContent=`${state.status==="live"?"🔴":"⏱️"} ${state.session[0]} · ${formatSpainTime(state.session[1])}`;renderSessionList(state.race);startCountdown(state.start,timer.id);}else{name.textContent="Temporada finalizada";timer.textContent="🏁";}
  const moto=getNextMotoGP(),mName=document.getElementById("motogp-name"),mPlace=document.getElementById("motogp-circuit"),mTimer=document.getElementById("motogp-countdown");if(moto){mName.textContent=moto.name;mPlace.textContent=`📍 ${moto.circuit}`;startMotoCountdown(new Date(moto.date).getTime(),mTimer.id);}
  renderEventHub();
  setInterval(checkHomeDataUpdate,60000);
});
async function checkHomeDataUpdate(){try{const response=await fetch(`sports-data.js?poll=${Date.now()}`,{cache:"no-store"});if(!response.ok)return;const source=await response.text(),revision=source.match(/updated:"([^"]+)"/)?.[1];if(revision&&revision!==footballData.updated)location.reload();}catch(error){console.info("Sincronización temporalmente no disponible.");}}
function renderEventHub(){const box=document.getElementById("event-hub");if(!box)return;const f1=getF1State(),moto=getNextMotoGP(),events=[];if(f1.race)events.push({icon:"🏎️",title:`${f1.race.name} · ${f1.session[0]}`,time:f1.start,url:"F1.html"});if(moto)events.push({icon:"🏍️",title:moto.name,time:new Date(moto.date).getTime(),url:"MotoGP.html"});(footballData.laligaRounds[footballData.currentRound]||[]).forEach(match=>{const live=isFootballLive(match),hasScore=Number.isInteger(match.homeScore)&&Number.isInteger(match.awayScore);events.push({icon:"⚽",title:live&&hasScore?`${match.home} ${match.homeScore}–${match.awayScore} ${match.away}`:`${match.home} – ${match.away}`,time:new Date(match.iso).getTime(),url:"deportes.html",teams:`${match.home}|${match.away}`,state:match.state});});const favourite=window.getFavouriteTeam?.();box.innerHTML=events.filter(e=>e.time>Date.now()-10800000).sort((a,b)=>{const af=favourite&&a.teams?.split("|").includes(favourite),bf=favourite&&b.teams?.split("|").includes(favourite);return (b.state==="live")-(a.state==="live")||bf-af||a.time-b.time;}).slice(0,3).map(e=>`<a class="timeline-event${e.state==="live"?" is-live":""}" href="${e.url}"${e.teams?` data-teams="${e.teams}"`:""}><span>${e.icon}</span><span><strong>${e.title}</strong><small>${new Intl.DateTimeFormat("es-ES",{weekday:"long",day:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Europe/Madrid"}).format(new Date(e.time))}</small></span><span class="event-state${e.state==="live"?" live":""}">${e.state==="live"?"🔴 EN JUEGO":e.time-Date.now()<86400000?"HOY":"PRÓXIMO"}</span></a>`).join("")||"<p>No hay eventos próximos confirmados.</p>";requestAnimationFrame(()=>window.applyTeamPreference?.());}
