(() => {
  const race=motogpCalendar.find(item=>item.id===new URLSearchParams(location.search).get("id"));
  const $=id=>document.getElementById(id),esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
  const pending=(title,detail="Esperando publicación o integración de datos oficiales.")=>`<div class="gp-pending-panel"><strong>${esc(title)}</strong><span>${esc(detail)}</span></div>`;
  if(!race){document.title="Gran Premio no encontrado · WOLFGAMES";$('gp-title').textContent="Gran Premio no encontrado";$('gp-country').textContent="No se encontró esa ficha";$('gp-status').textContent="ID no válido";$('gp-sessions').innerHTML=`<li class="gp-pending-session">${pending("Comprueba el calendario de MotoGP.")}</li>`;return;}
  document.title=`${race.name} · MotoGP · WOLFGAMES`;document.body.style.setProperty("--gp-accent",race.accent);
  $("gp-country").textContent=`${race.flag} ${race.country}`;$("gp-title").textContent=race.name;$("gp-circuit-name").textContent=race.circuit;$("gp-round").textContent=`${race.round} / ${motogpCalendar.length}`;$("gp-dates").textContent=race.label;$("gp-location").textContent=`${race.circuit} · ${race.country}`;
  const sessions=race.sessions||[];const lastEnd=motorsportRaceEnd("motogp",race);const now=Date.now();$("gp-status").textContent=now>lastEnd?"FIN DE SEMANA FINALIZADO":sessions.some(session=>motoSessionState(session,now)==="live")?"EN CURSO":now>new Date(race.date).getTime()?"PROGRAMA PENDIENTE":"PRÓXIMAMENTE";
  if(sessions.length){$("gp-sessions").innerHTML=sessions.map((session,index)=>{const view=motorsportSessionView("motogp",session),label={live:"EN DIRECTO",finished:"FINALIZADA",upcoming:"PRÓXIMA",pending:"PENDIENTE",postponed:"APLAZADA",cancelled:"CANCELADA"}[view.status]||"PENDIENTE",stamp=new Intl.DateTimeFormat("es-ES",{weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit",timeZone:window.WolfTimezone?.get()||"Europe/Madrid"}).format(new Date(view.start));return `<li class="gp-session ${view.status==="live"?"is-live":""}"><span class="gp-session-number">${String(index+1).padStart(2,"0")}</span><span class="gp-session-info"><strong>${esc(view.name)}</strong><small>${esc(stamp)}</small></span><span class="status">${label}</span></li>`;}).join("");}else{$("gp-sessions").innerHTML=`<li class="gp-pending-session">${pending("Programa oficial pendiente","El calendario confirma el fin de semana; los horarios de sesiones aún no están disponibles.")}</li>`;}
  $("gp-results").innerHTML=sessions.map(session=>`<article class="gp-result-panel" id="session-${encodeURIComponent(session.name).replaceAll("%","-")}"><div><p class="eyebrow">${esc(session.name)}</p><h3>Clasificación de sesión</h3></div>${pending("Resultados pendientes","Se añadirán cuando exista un resultado oficial publicado.")}</article>`).join("")||pending("Resultados pendientes","El programa detallado aún no está disponible.");
  const facts=[["01","Ganador","Pendiente"],["02","Podio","Pendiente"],["03","Pole","Pendiente"],["04","Vuelta rápida","Pendiente"],["05","Abandonos","Pendiente"],["06","Safety car / bandera roja","Pendiente"]];$("gp-race-data").innerHTML=facts.map(([n,label,value])=>`<div class="gp-fact"><span class="gp-fact-index">${n}</span><small>${label}</small><strong>${value}</strong></div>`).join("");
  $("gp-conditions").innerHTML=pending("Condiciones pendientes","Sin observaciones meteorológicas verificadas para mostrar.");$("gp-championship").innerHTML=pending("Impacto en campeonato pendiente","Se completará cuando haya clasificación oficial tras el Gran Premio.");
  function updateCountdown(){
    const session=motorsportNextSession("motogp",race,Date.now()),view=session?motorsportSessionView("motogp",session):null;
    $("gp-countdown-session").textContent=view?.name||(sessions.length?"Fin de semana finalizado":"Horarios detallados pendientes");
    $("gp-countdown-time").textContent=view?new Intl.DateTimeFormat("es-ES",{weekday:"long",day:"numeric",month:"long",hour:"2-digit",minute:"2-digit",timeZone:window.WolfTimezone?.get()||"Europe/Madrid"}).format(new Date(view.start)):sessions.length?"Resultados pendientes de integración oficial":`Fechas del GP: ${race.label} · hora de sesiones pendiente`;
    $("gp-countdown-state").textContent=view?.status==="live"?"EN DIRECTO":view?.status==="upcoming"?"PRÓXIMA":sessions.length?"FINALIZADO":"PENDIENTE";
    const kicker=document.querySelector(".gp-countdown-kicker");if(kicker)kicker.textContent=view?"PRÓXIMA SESIÓN":sessions.length?"DATOS DE CARRERA":"FIN DE SEMANA";
    const target=view?new Date(view.start).getTime():NaN,diff=target-Date.now(),values=Number.isFinite(diff)&&diff>0?[Math.floor(diff/86400000),Math.floor(diff%86400000/3600000),Math.floor(diff%3600000/60000),Math.floor(diff%60000/1000)]:["—","—","—","—"];
    ["gp-count-days","gp-count-hours","gp-count-minutes","gp-count-seconds"].forEach((id,i)=>$(id).textContent=values[i]==="—"?values[i]:String(values[i]).padStart(i?2:1,"0"));
  }
  updateCountdown();setInterval(()=>{if(!document.hidden)updateCountdown();},1000);
})();

