const WOLFGAMES_TEAMS=[["Athletic Club","ATH","#d71920"],["Atlético de Madrid","ATM","#e30613"],["CA Osasuna","OSA","#d91a2a"],["Celta","CEL","#68a9d4"],["Deportivo Alavés","ALA","#1261a0"],["Elche CF","ELC","#169447"],["FC Barcelona","BAR","#00a2e8"],["Getafe CF","GET","#005999"],["Levante UD","LEV","#e30613"],["Málaga CF","MGA","#59b8e8"],["R. Racing Club","RAC","#149447"],["Rayo Vallecano","RAY","#ef3340"],["RC Deportivo","DEP","#2574bb"],["RCD Espanyol de Barcelona","ESP","#2b9bd7"],["Real Betis","BET","#16a05d"],["Real Madrid","RMA","#f4c542"],["Real Sociedad","RSO","#1874bb"],["Sevilla FC","SEV","#e30613"],["Valencia CF","VAL","#ff7a00"],["Villarreal CF","VIL","#f3d400"]].map(([name,code,color])=>({name,code,color,competition:"laliga"}));
const TEAM_KEY="wolfgames-favourite-team";
const TEAM_ALIASES={"FC Barcelona":["Barcelona"],"Barcelona":["FC Barcelona"],"Paris":["Paris Saint-Germain"],"Paris Saint-Germain":["Paris"],"Man City":["Manchester City"],"Manchester City":["Man City"],"Man Utd":["Manchester United"],"Manchester United":["Man Utd"],"B. Dortmund":["Borussia Dortmund"],"Borussia Dortmund":["B. Dortmund"],"Atleti":["Atlético de Madrid"],"Atlético de Madrid":["Atleti"],"S. Bratislava":["Slovan Bratislava"],"Slovan Bratislava":["S. Bratislava"],"PSV":["PSV Eindhoven"],"PSV Eindhoven":["PSV"],"Shakhtar":["Shakhtar Donetsk"],"Shakhtar Donetsk":["Shakhtar"]};
function storedTeam(){const raw=localStorage.getItem(TEAM_KEY)||"";if(!raw)return null;try{const value=JSON.parse(raw);if(value?.name)return value;}catch{}return {name:raw,competition:"laliga"};}
function getFavouriteTeam(){return storedTeam()?.name||"";}
function favouriteNames(){const name=getFavouriteTeam();return new Set([name,...(TEAM_ALIASES[name]||[])]);}
function isFavouriteTeam(name){return favouriteNames().has(name);}
function championsTeams(){const rows=typeof championsData!=="undefined"?championsData.standings||[]:[];return rows.map(row=>({name:row.team,code:String(row.team).split(/\s+/).map(word=>word[0]).join("").slice(0,3).toUpperCase(),color:"#22d3ee",competition:"champions"}));}
function availableTeams(){const seen=new Set;return [...WOLFGAMES_TEAMS,...championsTeams()].filter(team=>{const key=team.competition+"|"+team.name;if(seen.has(key))return false;seen.add(key);return true;});}
function teamDetails(){const saved=storedTeam();return availableTeams().find(team=>team.name===saved?.name&&team.competition===saved?.competition)||availableTeams().find(team=>team.name===saved?.name)||null;}
function applyTeamPreference(){const team=teamDetails();document.documentElement.style.removeProperty("--team-accent");document.querySelectorAll(".favourite-team").forEach(el=>el.classList.remove("favourite-team"));document.querySelectorAll(".favourite-badge").forEach(el=>el.remove());if(!team)return;document.documentElement.style.setProperty("--team-accent",team.color);document.querySelectorAll("[data-teams]").forEach(el=>{const match=el.dataset.teams.split("|").some(isFavouriteTeam);el.classList.toggle("favourite-team",match);});document.querySelectorAll("[data-team]").forEach(el=>el.classList.toggle("favourite-team",isFavouriteTeam(el.dataset.team)));}
function teamOptions(){const groups=[["laliga","LALIGA"],["champions","Champions League"]];return groups.map(([key,label])=>{const teams=availableTeams().filter(team=>team.competition===key).sort((a,b)=>a.name.localeCompare(b.name,"es"));return teams.length?`<optgroup label="${label}">${teams.map(team=>`<option value="${key}|${team.name}">${team.name}</option>`).join("")}</optgroup>`:"";}).join("");}
function competitionCatalog(){const items=window.SportsWidget?.catalog()||[];return items.length?items:[{id:"laliga",label:"LaLiga",icon:"⚽"},{id:"champions",label:"Champions",icon:"🏆"},{id:"f1",label:"F1",icon:"🏎️"},{id:"motogp",label:"MotoGP",icon:"🏍️"}];}
function competitionOptions(){return competitionCatalog().map(item=>`<label class="competition-option"><input type="checkbox" name="competition" value="${item.id}"><span>${item.icon} ${item.label}</span></label>`).join("");}
function buildTeamPreferences(){const header=document.querySelector(".site-header");if(!header)return;const button=document.createElement("button");button.className="team-trigger";button.type="button";button.setAttribute("aria-label","Personalizar equipo y competiciones");button.innerHTML=`<span aria-hidden="true">⚽</span><span>${teamDetails()?.code||"Mis deportes"}</span>`;header.insertBefore(button,header.querySelector(".menu-toggle"));document.body.insertAdjacentHTML("beforeend",`<dialog id="team-dialog" class="team-dialog"><form method="dialog"><button class="dialog-close" value="cancel" aria-label="Cerrar">×</button><p class="eyebrow">Personaliza WOLFGAMES</p><h2>Mis competiciones</h2><p>Elige qué deportes y ligas aparecen en la agenda. La selección se guarda únicamente en este dispositivo.</p><fieldset class="competition-picker"><legend>Mostrar en mi agenda</legend>${competitionOptions()}</fieldset><div class="dialog-actions"><button class="btn-link" id="save-competitions" value="default">Guardar competiciones</button></div><hr><h3>Equipo favorito</h3><p>Destacaremos sus partidos, resultados y posición en LALIGA y Champions.</p><label for="team-select">Equipo favorito</label><select id="team-select"><option value="">Ningún equipo</option>${teamOptions()}</select><div class="dialog-actions"><button class="btn-link" id="save-team" value="default">Guardar equipo</button><button class="text-button" id="clear-team" type="button">Eliminar equipo</button></div></form></dialog>`);const dialog=document.getElementById("team-dialog"),select=document.getElementById("team-select"),checks=[...dialog.querySelectorAll('input[name="competition"]')];button.addEventListener("click",()=>{const saved=storedTeam();select.innerHTML='<option value="">Ningún equipo</option>'+teamOptions();select.value=saved?`${saved.competition}|${saved.name}`:"";const chosen=new Set(window.SportsWidget?.selected()||checks.map(item=>item.value));checks.forEach(input=>input.checked=chosen.has(input.value));dialog.showModal();});document.getElementById("save-competitions").addEventListener("click",event=>{event.preventDefault();const ids=checks.filter(input=>input.checked).map(input=>input.value);if(window.SportsWidget)window.SportsWidget.setSelected(ids);else{try{localStorage.setItem("wolfgames-selected-competitions",JSON.stringify(ids));}catch{}}dialog.close();location.reload();});document.getElementById("save-team").addEventListener("click",event=>{event.preventDefault();const [competition,...parts]=select.value.split("|"),name=parts.join("|");if(name)localStorage.setItem(TEAM_KEY,JSON.stringify({name,competition}));else localStorage.removeItem(TEAM_KEY);dialog.close();location.reload();});document.getElementById("clear-team").addEventListener("click",()=>{localStorage.removeItem(TEAM_KEY);dialog.close();location.reload();});applyTeamPreference();}
window.getFavouriteTeam=getFavouriteTeam;window.isFavouriteTeam=isFavouriteTeam;window.applyTeamPreference=applyTeamPreference;
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",buildTeamPreferences);else buildTeamPreferences();
