(()=>{
"use strict";
const API="https://api.github.com/repos/Steven2506/CONTENIDO-DEPORTIVO/actions/runs?per_page=100";
const watched=[
{name:"Actualizar resultados LALIGA",label:"Resultados LALIGA",maxAge:6},
{name:"Actualizar Champions League",label:"Champions League",maxAge:6},
{name:"Actualizar árbitros RFEF",label:"Árbitros y VAR",maxAge:8},
{name:"Validar web",label:"Pruebas automáticas",maxAge:48},
{name:"pages build and deployment",label:"Publicación GitHub Pages",maxAge:48}
];
const esc=value=>String(value==null?"":value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const dateText=value=>new Intl.DateTimeFormat("es-ES",{dateStyle:"medium",timeStyle:"short",timeZone:window.WolfTimezone&&WolfTimezone.get?WolfTimezone.get():"Europe/Madrid"}).format(new Date(value));
const ageHours=value=>(Date.now()-new Date(value).getTime())/36e5;
function resultState(run,maxAge){if(!run)return{kind:"warning",label:"Sin información"};if(run.status!=="completed")return{kind:"running",label:"En curso"};if(run.conclusion!=="success")return{kind:"error",label:"Error"};if(ageHours(run.updated_at||run.created_at)>maxAge)return{kind:"warning",label:"Sin ejecución reciente"};return{kind:"ok",label:"Operativo"};}
function workflowCard(item,run){const state=resultState(run,item.maxAge),detail=run?dateText(run.updated_at||run.created_at):"GitHub no devolvió ejecuciones";return '<article class="health-card '+state.kind+'"><div class="health-card-heading"><span class="health-dot" aria-hidden="true"></span><span class="health-badge">'+state.label+'</span></div><h3>'+item.label+'</h3><p>Última comprobación: '+detail+'</p></article>';}
function dataChecks(){const league=Object.values(typeof footballData!=="undefined"&&footballData.laligaRounds?footballData.laligaRounds:{}).flat(),champions=typeof officialChampionsFixtures!=="undefined"?officialChampionsFixtures:[],all=[...league,...champions],finalWithoutScore=all.filter(match=>(match.state==="finished"||match.status==="Finalizado")&&(!Number.isInteger(match.homeScore)||!Number.isInteger(match.awayScore))),staleLive=all.filter(match=>match.state==="live"&&match.iso&&Date.now()-new Date(match.iso).getTime()>4*36e5),badMinutes=league.filter(match=>{if(match.minute==null)return false;if(typeof match.minute==="number")return match.minute<0||match.minute>130;const parsed=String(match.minute).match(/^(45|90|105|120)\+(\d{1,2})$/);return !parsed||Number(parsed[2])>20;}),scheduled=all.filter(match=>match.state==="scheduled"||!match.state).length;return[
{label:"Marcadores finales",ok:!finalWithoutScore.length,value:finalWithoutScore.length?finalWithoutScore.length+" incompletos":all.filter(m=>m.state==="finished"||m.status==="Finalizado").length+" verificados"},
{label:"Partidos en directo",ok:!staleLive.length,value:staleLive.length?staleLive.length+" atascados":"Sin directos atascados"},
{label:"Minutos y añadidos",ok:!badMinutes.length,value:badMinutes.length?badMinutes.length+" incoherentes":"Formatos correctos"},
{label:"Calendario disponible",ok:league.length>0&&champions.length>0,value:league.length+" LALIGA · "+champions.length+" Champions"},
{label:"Próximos encuentros",ok:scheduled>0,value:scheduled+" programados"}];}
function renderData(){const checks=dataChecks();document.getElementById("data-health").innerHTML=checks.map(check=>'<article class="health-card '+(check.ok?"ok":"error")+'"><div class="health-card-heading"><span class="health-dot" aria-hidden="true"></span><span class="health-badge">'+(check.ok?"Correcto":"Atención")+'</span></div><h3>'+check.label+'</h3><p>'+check.value+'</p></article>').join("");return checks.every(check=>check.ok);}
async function refresh(){const button=document.getElementById("health-refresh");button.disabled=true;button.textContent="Actualizando…";const dataOk=renderData();try{const response=await fetch(API,{headers:{Accept:"application/vnd.github+json"},signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error("GitHub respondió "+response.status);const payload=await response.json(),latest=new Map();for(const run of payload.workflow_runs||[])if(!latest.has(run.name))latest.set(run.name,run);const states=watched.map(item=>({item,run:latest.get(item.name)}));document.getElementById("workflow-health").innerHTML=states.map(entry=>workflowCard(entry.item,entry.run)).join("");const workflowsOk=states.every(entry=>resultState(entry.run,entry.item.maxAge).kind==="ok"),allOk=dataOk&&workflowsOk;document.getElementById("health-light").className="health-light "+(allOk?"ok":"warning");document.getElementById("health-title").textContent=allOk?"Todos los sistemas operativos":"El sistema requiere atención";document.getElementById("health-detail").textContent=allOk?"Automatizaciones recientes y datos deportivos coherentes.":"Revisa las tarjetas marcadas antes de confiar en la siguiente actualización.";}catch(error){document.getElementById("workflow-health").innerHTML='<article class="health-card warning"><h3>No se pudo consultar GitHub</h3><p>'+esc(error.message)+'. Los controles locales sí se han ejecutado.</p></article>';document.getElementById("health-light").className="health-light warning";document.getElementById("health-title").textContent=dataOk?"Datos correctos; estado remoto no disponible":"El sistema requiere atención";document.getElementById("health-detail").textContent="La consulta pública a GitHub no respondió. Inténtalo de nuevo más tarde.";}finally{button.disabled=false;button.textContent="Actualizar estado";}}
document.addEventListener("DOMContentLoaded",()=>{refresh();document.getElementById("health-refresh").addEventListener("click",refresh);});
})();